config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "photos#index"

  resources :photos do
  	resources :comments
    resources :likes
  end

  resources :payments
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      can :read, :all
    else
      can :read, :all
      can :create, Photo
      can [:update, :destroy], Photo, :user_id => user.id
      can :create, Comment
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user

end

app/models/customer.rb
class IGCustomer

	def self.new_with(email, card)
		customer = Stripe::Customer.create(
			:email 	=> email,
			:card 	=> card
		)
	end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
  validates :user_id, :uniqueness => {:scope => :photo_id}
end

app/models/payment.rb
class Payment
	
	# Amount in cents
	def self.charge(customer, amount)
		payment = Stripe::Charge.create(
			:customer 		=> customer.id,
			:amount 			=> amount,
			:description 	=> 'Instachegram picture purchase',
			:currency 		=> 'usd'
		)
	end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

	belongs_to :user
	has_many :likes
	has_many :comments
	has_attached_file :image, styles: {large: "500x500"}, :default_url => "/images/:style/squares.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :photos
  has_many :likes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
	end

	def new
	  @photo = Photo.find(params[:photo_id])
	  @comment = Comment.new
	end

	def create
	  @photo = Photo.find(params[:photo_id])
	  @comment = @photo.comments.new(comment_params)
	  if current_user
	  	@comment.user_id = current_user.id
	  	@comment.save
	  	redirect_to photos_path
	  else
	  	flash[:notice] = "You have to be logged in to comment."
	  	redirect_to new_photo_comment_path
	  end
	end

	def comment_params
	  params.require(:comment).permit(:thoughts)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
    @photo = Photo.find(params[:photo_id])
    like = @photo.likes.new
    like.user_id = current_user.id
    if like.save
    	render json: { new_like_count: @photo.likes.count }
    else
      flash[:notice] = "You already liked this photo."
    	redirect_to photos_path	
    end
  end

  # def destroy
  # 	@like = current_user.likes.find(params[:photo_id])
  # 	render json: { new_like_count: @photo.likes.count }	if @like.destroy
  # end 

end

app/controllers/payments_controller.rb
require_relative '../models/customer'

class PaymentsController < ApplicationController
	
	def new
	end

	def create
		@amount = 100
		customer = IGCustomer.new_with(params[:email], params[:stripeToken])
		payment = Payment.charge(customer, @amount)
	end

rescue Stripe::CardError => e
	flash[:error] = e.message
	redirect_to charges_path

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	before_action :authenticate_user!, :except => [:index, :show]

	def index
		@photos = Photo.all
	end

	def new
		@photo = Photo.new
	end

	def create
		if current_user
			@photo = Photo.new(params[:photo].permit(:image, :caption))
			@photo.user_id = current_user.id
		end

		if @photo.save
			redirect_to photos_path
		else
			render 'new'
		end
	end

	def edit
		@photo = Photo.find(params[:id])
	end

	def update
		@photo = current_user.photos.find(params[:id])
    @photo.update(params[:photo].permit(:caption))
    redirect_to photos_path
	end

	def destroy
		@photo = current_user.photos.find(params[:id])
		@photo.destroy
		flash[:notice] = "Photo was deleted successfully"
		redirect_to photos_path
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/new.html.erb
<%= form_for [@photo, @comment] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.submit 'Leave Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Instachegram</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<header>
			<a href="/"><img id="banner" src="/images/banner.jpg"></a>
		</header>
		
		<section id="nav_links">
			<% if user_signed_in? %>
				<%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'user_links' %>
			<% else %>
				<%= link_to "Sign in", new_user_session_path, class: 'user_links' %> | 
				<%= link_to "Sign up", new_user_registration_path, class: 'user_links' %> |
				<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), class: 'user_links' %>
			<% end %>
		</section>
		<h2>Welcome to Instachegram</h2>
		<h4>A photo-sharing social media site for mustaches</h4>

		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		<p class="error"><%= flash[:error] %></p>
	

		<%= yield %>

	</body>
</html>

app/views/layouts/payments.html.erb
<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
	  <%= yield %>
	</body>
</html>

app/views/payments/create.html.erb
<h2>Thanks, you paid <strong>$1.00</strong>!</h2>

app/views/payments/new.html.erb
<%= form_tag payments_path do %>
  <article>
    <label class="amount">
      <span>Amount: $1.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Buy photo"
          data-amount="100"></script>
<% end %>

app/views/photos/edit.html.erb
<%= form_for @photo do |f| %>
	<%= f.label :caption %>
	<%= f.text_field :caption %><br>
	<%= f.submit %>
<% end %>

app/views/photos/index.html.erb
<p><%= link_to 'Add a photo', new_photo_path %></p>

<% if @photos.any? %>
	<% @photos.reverse.each do |photo| %>
		<section class="photo">
			<p>
				<%= image_tag(photo.image.url(:large)) %><br>
				<%= photo.user.email %> | <%= photo.caption %> 
				<span class="likes_count"><br><%= photo.likes.count %></span> likes
				<%= link_to 'Like', photo_likes_path(photo), class: 'likes-link' %> 
			</p>
			<% if photo.comments.any? %>
				<% photo.comments.each do |comment| %>
					<%= comment.user.email %>: <%= comment.thoughts %><br>
				<% end %>
			<% end %>
			<%= link_to 'Comment', new_photo_comment_path(photo) %>
			<%= link_to 'Edit caption', edit_photo_path(photo) if can?(:update, photo) %><br>
			<%= link_to 'Delete photo', photo_path(photo), method: :delete if can?(:destroy, photo) %></p>
		</section>
	<% end %>
<% else %>
	No photos (yet).
<% end %>

app/views/photos/new.html.erb
Upload your photo: 
<%= form_for Photo.new do |f| %>
	<%= f.label :image %>
	<%= f.file_field :image %><br>
	<%= f.label :caption %>
	<%= f.text_field :caption %><br>
	<%= f.submit %>
<% end %>